"""empty message

Revision ID: 4eb2cebfceeb
Revises: 4969288aa6ce
Create Date: 2022-04-10 12:59:52.659163

"""
from alembic import op # op = operation
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb2cebfceeb'
down_revision = '4969288aa6ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("INSERT INTO todolists (name) VALUES ('Uncategorized')")
    op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=True, default=1))
    op.alter_column('todos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_foreign_key(None, 'todos', 'todolists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey') 
    op.alter_column('todos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('todos', 'list_id')
    op.drop_table('todolists')
    # ### end Alembic commands ###
